export type Lang = "en" | "fr";

const strings: Record<Lang, Record<string, string>> = {
  en: {
    daily_digest: "AI Safety Daily Brief",
    weekly_digest: "AI Safety Weekly Digest",
    arxiv_section: "ArXiv Papers",
    github_section: "GitHub Activity",
    rss_section: "Blog Posts & Articles",
    web_section: "Organization Updates",
    hn_section: "Hacker News Discussions",
    no_updates: "No significant updates found.",
    generated_by: "Generated by AI Safety Daily Brief",
  },
  fr: {
    daily_digest: "Veille IA Safety - Digest Quotidien",
    weekly_digest: "Veille IA Safety - Digest Hebdomadaire",
    arxiv_section: "Articles ArXiv",
    github_section: "Activite GitHub",
    rss_section: "Billets de Blog & Articles",
    web_section: "Mises a jour des Organisations",
    hn_section: "Discussions Hacker News",
    no_updates: "Aucune mise a jour significative trouvee.",
    generated_by: "Genere par AI Safety Daily Brief",
  },
};

export function t(key: string, lang: Lang = "en"): string {
  return strings[lang]?.[key] ?? strings.en[key] ?? key;
}
